# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:

- job: linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    submodules: recursive

  - script: |
      set -o errexit -o pipefail
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
      sudo apt-get update
      sudo apt-get install --yes --no-install-recommends llvm clang-format clang-tidy clang libomp-dev python3 python3-setuptools openjdk-16-jdk libboost-dev samtools xz-utils bzip2 lrzip
      sudo pip3 install ninja meson cmake
    displayName: 'Install required software'

  - script: meson setup build && cd build && ninja
    displayName: 'Build the project'

  - script: cd build && ninja clang-format-check
    displayName: 'Run clang-format'

  - script: cd build && ninja clang-tidy
    displayName: 'Run clang-tidy'

  - script: |
      cd build && meson test --repeat=10
      if [[ $? -ne 0 ]]; then
        cat meson-logs/testlog.txt
        exit 1
      fi
    displayName: 'Run tests'

  - script: |
      cd build && ninja sanitize-undefined
      if [[ $? -ne 0 ]]; then
        cat __build-sanitize-undefined/meson-logs/testlog.txt
        exit 1
      fi
    displayName: 'Sanitize undefined'

  - script: |
      set -o errexit -o pipefail
      ./compile
      cd build && ninja test-wrappers
    displayName: 'Test wrappers'

- job: macos
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    submodules: recursive

  - script: |
      set -o errexit -o pipefail
      brew update
      brew install llvm libomp boost samtools coreutils xz lrzip
      brew tap adoptopenjdk/openjdk
      brew install --cask adoptopenjdk11
      sudo ln -sf $(brew --prefix llvm)/bin/clang-format /usr/local/bin/clang-format
      sudo ln -sf $(brew --prefix llvm)/bin/clang-tidy /usr/local/bin/clang-tidy
      sudo pip3 install ninja meson cmake
    displayName: 'Install required software'

  - script: meson setup build && cd build && ninja
    displayName: 'Build the project'

  - script: cd build && ninja clang-format-check
    displayName: 'Run clang-format'

  - script: cd build && ninja clang-tidy
    displayName: 'Run clang-tidy'

  - script: |
      cd build && meson test --repeat=10
      if [[ $? -ne 0 ]]; then
        cat meson-logs/testlog.txt
        exit 1
      fi
    displayName: 'Run tests'

  - script: |
      cd build && ninja sanitize-undefined
      if [[ $? -ne 0 ]]; then
        cat __build-sanitize-undefined/meson-logs/testlog.txt
        exit 1
      fi
    displayName: 'Sanitize undefined'

  - script: |
      set -o errexit -o pipefail
      ./compile
      cd build && ninja test-wrappers
    displayName: 'Test wrappers'